fix: UiScale a11y improvements
infermedica/component-library pull request #375
Opened 2024-02-22 12:41 UTC by jbucior

## Description
- Add/change aria-labels
- Add/change aria-labelledby
- Add aria-checked and role radio to UiRadio element
- Change default min and max value to more generic

## Related Issue

Closes #

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-02-22 12:49 UTC, pspaczek commented
@jbucior please add the issue. Because I don't know why we need these changes.

2024-02-22 13:35 UTC, sonya0504 submitted a review, later dismissed

2024-02-22 13:47 UTC, pspaczek requested changes
Please check my comment @jbucior

2024-02-22 13:47 UTC, pspaczek commented on src/components/molecules/UiScale/UiScale.vue
> +          id="scale-legend"
@jbucior `id` should be unique what about when dev put 2 `UiScale` on view ;) 
IMO should be 
```
const scaleId = computed(() => (
  props.id || `scale-${uid()}`
));

2024-02-22 13:47 UTC, pspaczek commented on src/components/molecules/UiScale/UiScale.vue
> +          id="scale-legend"
```suggestion
          :id="scaleId"
```

2024-02-22 13:47 UTC, pspaczek commented on src/components/molecules/UiScale/UiScale.vue
> +    :aria-labelledby="legend ? 'scale-legend' : undefined"
```suggestion
    :aria-labelledby="scaleId"
```

2024-02-22 13:47 UTC, pspaczek commented on src/components/molecules/UiScale/UiScale.vue
> +          role="radio"
? You get `<label role="radio" aria-checked="true"><input type="radio/></label>`. IMO it's not expected result. And I found that https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-checked

> Note: Where possible use an HTML [<input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) element with type="checkbox" as this element has built in semantics and does not require ARIA attributes.

2024-02-22 15:22 UTC, jbucior commented on src/components/molecules/UiScale/UiScale.vue
> +          id="scale-legend"
Removed

2024-02-23 07:42 UTC, pspaczek approved these changes
<img src="https://media2.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif"/>

2024-02-23 07:44 UTC, merged