feat: move list item suffix outside radio label
infermedica/component-library pull request #86
Opened 2023-01-10 13:25 UTC by mateuszkulpa

# Related issue
Close #84 

# Scope of work
- remove the tabindex=-1 attribute from the info button
- moved the info button outside of the radio label element

# Screenshots
![ezgif-3-e45b47b6a8](https://user-images.githubusercontent.com/17556031/211563404-46c45a03-087b-4b2e-a31f-7b07e888d6ed.gif)
![ezgif-3-c8e74420be](https://user-images.githubusercontent.com/17556031/211563416-0da77657-cd12-438e-b11b-a7a398d7316b.gif)

2023-01-12 15:24 UTC, pspaczek requested changes
After these changes, we get a lot of bugs to fix. 
We want to use a list with a suffix inside `<component>`.

2023-01-12 15:25 UTC, mateuszkulpa commented
> @mateuszkulpa this approach is approved by someone? Because the previous approach is implemented and user can use the arrow to move to the information button.
@pspaczek No, anyone approved it. But this solution is based on recommendations from accessibility auditors.
Please look at page 40 of the audit.

2023-01-12 15:28 UTC, mateuszkulpa commented on src/components/organisms/UiList/_internal/UiListItem.vue
> -        <!-- @slot Use this slot to replace suffix template -->
@pspaczek 
Sure, I'll fix it. But first, please check the auditors' recommendations. I want to be sure you agree with these hints.

2023-01-13 08:34 UTC, pspaczek commented
ok, I can agree with the second part of the issue. Button can't be inside <label/> but still, your solution makes a bug 
![Zrzut ekranu 2023-01-13 o 09 07 00](https://user-images.githubusercontent.com/12138170/212269786-7a46e7cb-e436-498f-847f-85077435d8bf.png)
the label should be full-width. IMO to solve this issue we should use content slot of UiListItem and put to it label (with class list-item-conten) and button. We can use grid or position absolute to put button in right place and do something with `ui-multiple-answer-item__label` add required spacing etc. 
IMO tabindex=-1 it should be stay. We need to investigate again how to handle this issue (checkbox/radio) with info button. 
* it can be ok for checkbox because user use tab to go to next. 
* it can't be work for radio because user use arrow to move to radios inside group (or I miss something)

2023-01-18 12:54 UTC, mateuszkulpa commented
@pspaczek I applied your suggestions. Suffix button is absolutely positioned.
Also, I removed changes regarding tabindex and keyboard navigation with arrows works fine.

2023-02-20 11:13 UTC, pspaczek approved these changes

2023-02-20 11:13 UTC, pspaczek commented on src/components/organisms/UiMultipleAnswer/_internal/UiMultipleAnswerItem.vue
> +  &--has-info {
@mateuszkulpa I made a few improvements to your solution.
Your solution:
```
.ui-multiple-answer-item {
  $this: &;
  $element: multiple-answer-item;

  &__label {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;

    @include mixins.use-logical($element + "-label", margin, 0 var(--space-32) 0 0);
  }

  &__suffix {
    --list-item-suffix-margin-inline: #{functions.var($element + "-suffix", margin-inline, var(--space-12))};

    position: #{functions.var($element + "-suffix", position, absolute)};
    inset-inline-end: #{functions.var($element + "-suffix", inset-inline-end, 0)};
  }
}
```

2023-02-20 11:13 UTC, pspaczek commented on src/components/organisms/UiMultipleAnswer/_internal/UiMultipleAnswerItem.vue
> +    #{$this}__label {
this after element allow us to keep required spacings (for example margin) for suffix element

2023-02-20 11:13 UTC, pspaczek commented on src/components/organisms/UiMultipleAnswer/_internal/UiMultipleAnswerItem.vue
> +    position: absolute;
without variables because IMO is static and user won't to change it

2023-02-20 11:13 UTC, pspaczek commented on src/components/organisms/UiMultipleAnswer/_internal/UiMultipleAnswerItem.vue
> +    @include mixins.use-logical("list-item-content", padding, var(--space-12) var(--space-20));
to keep relation between `ui-list-item-content` and spacings of this absolute positioning element. User can change only `ui-list-item-content-paddin` and doesn't have to worry to adjusting spaces of this suffix element

2023-02-20 13:46 UTC, merged